/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Vistas;

/**
 *
 * @author sebastian
 */
public class PrincipalCliente extends javax.swing.JFrame {

    /** Creates new form PrincipalCliente */
    public PrincipalCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCompras = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnProductoUno = new javax.swing.JButton();
        btnProductoDos = new javax.swing.JButton();
        btnProductoTres = new javax.swing.JButton();
        btnProductoCuatro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnAll = new javax.swing.JButton();
        ProductoCuatro = new javax.swing.JPanel();
        btnComprar4 = new javax.swing.JButton();
        ProductoCinco = new javax.swing.JPanel();
        btnComprar5 = new javax.swing.JButton();
        ProductoDiez = new javax.swing.JPanel();
        btnComprar10 = new javax.swing.JButton();
        ProductoNueve = new javax.swing.JPanel();
        btnComprar9 = new javax.swing.JButton();
        ProductoOcho = new javax.swing.JPanel();
        btnComprar8 = new javax.swing.JButton();
        ProductoTres = new javax.swing.JPanel();
        btnComprar3 = new javax.swing.JButton();
        ProductoDos = new javax.swing.JPanel();
        btnComprar2 = new javax.swing.JButton();
        ProductoSiete = new javax.swing.JPanel();
        btnComprar7 = new javax.swing.JButton();
        ProductoUno = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        ProductoSeis = new javax.swing.JPanel();
        btnComprar6 = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnCompras.setBackground(new java.awt.Color(255, 255, 255));
        btnCompras.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCompras.setForeground(new java.awt.Color(0, 0, 0));
        btnCompras.setText("Compras");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(255, 255, 255));
        btnPedidos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnProductoUno.setBackground(new java.awt.Color(255, 255, 255));
        btnProductoUno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProductoUno.setForeground(new java.awt.Color(0, 0, 0));
        btnProductoUno.setText("Producto Uno");
        btnProductoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoUnoActionPerformed(evt);
            }
        });

        btnProductoDos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductoDos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProductoDos.setForeground(new java.awt.Color(0, 0, 0));
        btnProductoDos.setText("Producto Dos");
        btnProductoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoDosActionPerformed(evt);
            }
        });

        btnProductoTres.setBackground(new java.awt.Color(255, 255, 255));
        btnProductoTres.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProductoTres.setForeground(new java.awt.Color(0, 0, 0));
        btnProductoTres.setText("Producto Tres");
        btnProductoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoTresActionPerformed(evt);
            }
        });

        btnProductoCuatro.setBackground(new java.awt.Color(255, 255, 255));
        btnProductoCuatro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnProductoCuatro.setForeground(new java.awt.Color(0, 0, 0));
        btnProductoCuatro.setText("Producto Cuatro");
        btnProductoCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoCuatroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Carrito de compras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(btnProductoUno, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(btnProductoTres, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(btnProductoCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(btnProductoDos, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnProductoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnProductoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnProductoTres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnProductoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INVETRONIX");

        btnCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("--Cliente--");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Monto");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 840, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(90, 90, 90)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCliente)
                    .addComponent(jLabel3))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        btnAll.setBackground(new java.awt.Color(255, 255, 255));
        btnAll.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAll.setForeground(new java.awt.Color(153, 153, 153));
        btnAll.setText("All");

        btnComprar4.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar4.setText("Comprar");
        btnComprar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoCuatroLayout = new javax.swing.GroupLayout(ProductoCuatro);
        ProductoCuatro.setLayout(ProductoCuatroLayout);
        ProductoCuatroLayout.setHorizontalGroup(
            ProductoCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCuatroLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(btnComprar4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        ProductoCuatroLayout.setVerticalGroup(
            ProductoCuatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCuatroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar4)
                .addGap(25, 25, 25))
        );

        btnComprar5.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar5.setText("Comprar");
        btnComprar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoCincoLayout = new javax.swing.GroupLayout(ProductoCinco);
        ProductoCinco.setLayout(ProductoCincoLayout);
        ProductoCincoLayout.setHorizontalGroup(
            ProductoCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoCincoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnComprar5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        ProductoCincoLayout.setVerticalGroup(
            ProductoCincoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoCincoLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(btnComprar5)
                .addGap(27, 27, 27))
        );

        btnComprar10.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar10.setText("Comprar");
        btnComprar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoDiezLayout = new javax.swing.GroupLayout(ProductoDiez);
        ProductoDiez.setLayout(ProductoDiezLayout);
        ProductoDiezLayout.setHorizontalGroup(
            ProductoDiezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoDiezLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnComprar10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        ProductoDiezLayout.setVerticalGroup(
            ProductoDiezLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoDiezLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar10)
                .addGap(25, 25, 25))
        );

        btnComprar9.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar9.setText("Comprar");
        btnComprar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoNueveLayout = new javax.swing.GroupLayout(ProductoNueve);
        ProductoNueve.setLayout(ProductoNueveLayout);
        ProductoNueveLayout.setHorizontalGroup(
            ProductoNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoNueveLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(btnComprar9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        ProductoNueveLayout.setVerticalGroup(
            ProductoNueveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoNueveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar9)
                .addGap(21, 21, 21))
        );

        btnComprar8.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar8.setText("Comprar");
        btnComprar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoOchoLayout = new javax.swing.GroupLayout(ProductoOcho);
        ProductoOcho.setLayout(ProductoOchoLayout);
        ProductoOchoLayout.setHorizontalGroup(
            ProductoOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoOchoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnComprar8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        ProductoOchoLayout.setVerticalGroup(
            ProductoOchoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoOchoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar8)
                .addGap(22, 22, 22))
        );

        btnComprar3.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar3.setText("Comprar");
        btnComprar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoTresLayout = new javax.swing.GroupLayout(ProductoTres);
        ProductoTres.setLayout(ProductoTresLayout);
        ProductoTresLayout.setHorizontalGroup(
            ProductoTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoTresLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnComprar3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        ProductoTresLayout.setVerticalGroup(
            ProductoTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoTresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar3)
                .addGap(25, 25, 25))
        );

        btnComprar2.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar2.setText("Comprar");
        btnComprar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoDosLayout = new javax.swing.GroupLayout(ProductoDos);
        ProductoDos.setLayout(ProductoDosLayout);
        ProductoDosLayout.setHorizontalGroup(
            ProductoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoDosLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnComprar2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        ProductoDosLayout.setVerticalGroup(
            ProductoDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoDosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar2)
                .addGap(25, 25, 25))
        );

        btnComprar7.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar7.setText("Comprar");
        btnComprar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoSieteLayout = new javax.swing.GroupLayout(ProductoSiete);
        ProductoSiete.setLayout(ProductoSieteLayout);
        ProductoSieteLayout.setHorizontalGroup(
            ProductoSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductoSieteLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnComprar7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ProductoSieteLayout.setVerticalGroup(
            ProductoSieteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoSieteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar7)
                .addGap(27, 27, 27))
        );

        btnComprar.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoUnoLayout = new javax.swing.GroupLayout(ProductoUno);
        ProductoUno.setLayout(ProductoUnoLayout);
        ProductoUnoLayout.setHorizontalGroup(
            ProductoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoUnoLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        ProductoUnoLayout.setVerticalGroup(
            ProductoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoUnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnComprar)
                .addGap(25, 25, 25))
        );

        btnComprar6.setBackground(new java.awt.Color(102, 102, 102));
        btnComprar6.setText("Comprar");
        btnComprar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprar6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProductoSeisLayout = new javax.swing.GroupLayout(ProductoSeis);
        ProductoSeis.setLayout(ProductoSeisLayout);
        ProductoSeisLayout.setHorizontalGroup(
            ProductoSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoSeisLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(btnComprar6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        ProductoSeisLayout.setVerticalGroup(
            ProductoSeisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductoSeisLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(btnComprar6)
                .addGap(28, 28, 28))
        );

        txtBusqueda.setText("Busca tu producto...");

        btnBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(txtBusqueda)
                        .addGap(39, 39, 39)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProductoNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductoCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductoDiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductoUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductoNueve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoDiez, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductoSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnProductoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoUnoActionPerformed

    private void btnProductoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoDosActionPerformed

    private void btnProductoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoTresActionPerformed

    private void btnProductoCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductoCuatroActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnComprar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar2ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar2ActionPerformed

    private void btnComprar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar3ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar3ActionPerformed

    private void btnComprar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar4ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar4ActionPerformed

    private void btnComprar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar5ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar5ActionPerformed

    private void btnComprar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar6ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar6ActionPerformed

    private void btnComprar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar7ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar7ActionPerformed

    private void btnComprar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar8ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar8ActionPerformed

    private void btnComprar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar9ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar9ActionPerformed

    private void btnComprar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprar10ActionPerformed
        VistaComprasCliente cambio= new VistaComprasCliente();
        cambio.setVisible(true);
    }//GEN-LAST:event_btnComprar10ActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        HistorialComprasClientes cambio= new HistorialComprasClientes();
        cambio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProductoCinco;
    private javax.swing.JPanel ProductoCuatro;
    private javax.swing.JPanel ProductoDiez;
    private javax.swing.JPanel ProductoDos;
    private javax.swing.JPanel ProductoNueve;
    private javax.swing.JPanel ProductoOcho;
    private javax.swing.JPanel ProductoSeis;
    private javax.swing.JPanel ProductoSiete;
    private javax.swing.JPanel ProductoTres;
    private javax.swing.JPanel ProductoUno;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnComprar10;
    private javax.swing.JButton btnComprar2;
    private javax.swing.JButton btnComprar3;
    private javax.swing.JButton btnComprar4;
    private javax.swing.JButton btnComprar5;
    private javax.swing.JButton btnComprar6;
    private javax.swing.JButton btnComprar7;
    private javax.swing.JButton btnComprar8;
    private javax.swing.JButton btnComprar9;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProductoCuatro;
    private javax.swing.JButton btnProductoDos;
    private javax.swing.JButton btnProductoTres;
    private javax.swing.JButton btnProductoUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
